# Generated by Django 6.0.8 on 2026-09-18 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_alter_property_description_alter_property_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timestamp_str', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('GENESIS', 'Genesis Block'), ('PROPERTY_CREATE', 'Property Registration'), ('PROPERTY_UPDATE', 'Property Update'), ('TITLE_DEED_UPLOAD', 'Legal Title Deed Upload'), ('MEDIA_UPLOAD', 'Media & File Upload'), ('INQUIRY_RECEIVED', 'Client Inquiry / Lead Registered'), ('BOOKING_SCHEDULED', 'Site Visit / Booking Scheduled'), ('PROFILE_UPDATE', 'User Profile Update'), ('SECURITY_AUDIT', 'CIA Security Triad Verification')], default='SECURITY_AUDIT', max_length=60)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('data_payload', models.JSONField(default=dict)),
                ('data_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('block_hash', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Block',
                'verbose_name_plural': 'Blockchain Blocks',
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media_vault/%Y/%m/')),
                ('file_type', models.CharField(choices=[('PHOTO', 'Photo / PNG / JPG Image'), ('VIDEO', 'Video (MP4 / WebM / MOV)'), ('PDF', 'PDF Document'), ('WORD', 'Word Document (.doc / .docx)')], default='PHOTO', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(blank=True, help_text='Cryptographic SHA-256 fingerprint for CIA Integrity', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_media', to='dashboard.blockchainblock')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_uploads', to='properties.property')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INQUIRY', 'Client Inquiry / Message'), ('BOOKING', 'Booking Request'), ('TASK', 'Task Alert'), ('SECURITY', 'CIA Blockchain Alert'), ('SYSTEM', 'System Alert')], default='INQUIRY', max_length=30)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Leave empty to broadcast to all authorized staff/managers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
