# Generated by Django 6.0.8 on 2026-09-17 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Endely Estate phase 4 located at Wonya Mokomba', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, default='We are launching Endely Estate Phase 4 located at Wonya Mokomba in Buea, Cameroon.', max_length=350)),
                ('property_type', models.CharField(choices=[('LAND', 'Land / Plots'), ('RESIDENTIAL', 'Residential House'), ('VILLA', 'Luxury Villa'), ('COMMERCIAL', 'Commercial Property'), ('APARTMENT', 'Apartment')], default='LAND', max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available / Active'), ('UNDER_OFFER', 'Under Offer'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold Out')], default='AVAILABLE', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=2000000.0, max_digits=14)),
                ('currency', models.CharField(default='FCFA', max_length=15)),
                ('price_prefix', models.CharField(blank=True, default='From', max_length=50)),
                ('price_suffix', models.CharField(blank=True, default='per 400 m² plot', max_length=50)),
                ('area_sqm', models.DecimalField(decimal_places=2, default=400.0, max_digits=10)),
                ('area_display', models.CharField(default='400 m² (Acres and Hectares available)', max_length=100)),
                ('topography', models.CharField(default='Level / 100% Flat', max_length=100)),
                ('location', models.CharField(default='Wonya Mokomba, Buea, Cameroon', max_length=255)),
                ('city', models.CharField(default='Buea', max_length=100)),
                ('region', models.CharField(default='South West Region', max_length=100)),
                ('country', models.CharField(default='Cameroon', max_length=100)),
                ('description', models.TextField(default="Endely Estate Phase 4 at Wonya Mokomba is a prestigious master-planned estate situated in one of Buea's fastest developing corridors. Boasting 100% level topography, excellent motorable access roads, surveyed plot boundaries with permanent boundary pillars, and scenic vistas of Mount Cameroon. Ideal for executive villas, residential homes, and strategic land banking.")),
                ('documents', models.JSONField(default=list, help_text='List of official legal documents (e.g. Chief Attestation, Site Plan, Transfer of ownership, Deed)')),
                ('landmarks', models.JSONField(default=list, help_text='Key landmarks with drive times and descriptions')),
                ('features', models.JSONField(default=list, help_text='Key highlights, e.g. Level topography, electricity corridor, road access')),
                ('featured_image', models.CharField(default='images/hero.jpg', max_length=255)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo tour link')),
                ('is_featured', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
