# Generated by Django 6.0.8 on 2026-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default="We are proudly launching the prime property located behind Cathedral around Blue Empire in Buea, Cameroon. Strategically situated in Buea's fastest booming residential corridor, this property offers pristine, 100% level topography, direct motorable access, surveyed plot boundaries with permanent boundary pillars, and scenic vistas of Mount Cameroon. Guaranteed by Fred's Global Real Estate."),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='Behind Cathedral around Blue Empire, Buea, Cameroon', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='subtitle',
            field=models.CharField(blank=True, default='We are launching the prime property located behind Cathedral around Blue Empire in Buea, Cameroon.', max_length=350),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(default='Prime Property Located Behind Cathedral around Blue Empire', max_length=255),
        ),
    ]
