# Generated by Django 6.0.8 on 2026-09-16 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=300)),
                ('booking_datetime', models.DateTimeField()),
                ('booking_type', models.CharField(choices=[('VIEWING', 'Viewing'), ('CALL', 'Call'), ('MEETING', 'Meeting'), ('SITE_VISIT', 'Site Visit')], default='VIEWING', max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('NOSHOW', 'No-Show'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='contacts.contact')),
            ],
            options={
                'ordering': ['booking_datetime'],
            },
        ),
    ]
